"use client";
import { FormEvent, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
const systems=["Guest Inbox Pro","Digital Guest Concierge","Repeat Guest Engine","Direct Booking Engine"];
const goals=[["reply","Reduce repetitive guest messaging"],["repeat","Generate more repeat bookings"],["concierge","Improve the digital guest experience"],["direct","Increase direct bookings"]];
export default function RequestSetupForm(){
 const searchParams=useSearchParams(); const requested=searchParams.get("product")||"Repeat Guest Engine";
 const defaultProduct=useMemo(()=>systems.find(n=>n.toLowerCase().replaceAll(" ","-")===requested)||systems.find(n=>n===requested)||"Repeat Guest Engine",[requested]);
 const [product,setProduct]=useState(defaultProduct),[propertyName,setPropertyName]=useState(""),[contactName,setContactName]=useState(""),[email,setEmail]=useState(""),[website,setWebsite]=useState(""),[propertyType,setPropertyType]=useState("Hotel"),[rooms,setRooms]=useState(""),[currentStack,setCurrentStack]=useState(""),[databaseSize,setDatabaseSize]=useState(""),[notes,setNotes]=useState(""),[goal,setGoal]=useState("repeat"),[copied,setCopied]=useState(false);
 function buildRequest(){const goalLabel=goals.find(([id])=>id===goal)?.[1]||goal; const subject=`GuestFlow Systems - ${product} setup review`; const body=[`System: ${product}`,`Primary goal: ${goalLabel}`,`Property: ${propertyName||"-"}`,`Property type: ${propertyType||"-"}`,`Rooms / units: ${rooms||"-"}`,`Contact: ${contactName||"-"}`,`Email: ${email||"-"}`,`Website: ${website||"-"}`,`Current PMS / tools: ${currentStack||"-"}`,`Approx. past-guest database: ${databaseSize||"-"}`,"","Context / notes:",notes||"-"].join("\n"); return {subject,body};}
 function submit(e:FormEvent){e.preventDefault();const {subject,body}=buildRequest();window.location.href=`mailto:hello@guestflowsystems.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}
 async function copyRequest(){const {subject,body}=buildRequest();await navigator.clipboard.writeText(`${subject}\n\n${body}\n\nSend to: hello@guestflowsystems.com`);setCopied(true);window.setTimeout(()=>setCopied(false),2200);}
 return <form onSubmit={submit} className="setup-form">
  <div className="form-intro"><div><span className="eyebrow">2-minute review</span><h2>Start with the outcome.</h2></div><span className="form-trust">No obligation · No guest data required</span></div>
  <fieldset className="goal-picker"><legend>What would you most like to improve?</legend>{goals.map(([id,label])=><label key={id} className={goal===id?"goal-option selected":"goal-option"}><input type="radio" name="goal" value={id} checked={goal===id} onChange={()=>setGoal(id)}/><span>{label}</span></label>)}</fieldset>
  <label>System<select value={product} onChange={e=>setProduct(e.target.value)} className="setup-field">{systems.map(s=><option key={s}>{s}</option>)}</select></label>
  <div className="form-grid-2"><label>Property name<input required value={propertyName} onChange={e=>setPropertyName(e.target.value)} placeholder="Hotel / B&B name" className="setup-field"/></label><label>Property type<select value={propertyType} onChange={e=>setPropertyType(e.target.value)} className="setup-field"><option>Hotel</option><option>B&B</option><option>Guest house</option><option>Aparthotel</option><option>Apartments</option><option>Other</option></select></label></div>
  <div className="form-grid-2"><label>Your name / role<input required value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="Name and role" className="setup-field"/></label><label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@property.com" className="setup-field"/></label></div>
  <div className="form-grid-2"><label>Website<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://..." className="setup-field"/></label><label>Rooms / units<input value={rooms} onChange={e=>setRooms(e.target.value)} inputMode="numeric" placeholder="e.g. 24" className="setup-field"/></label></div>
  <details className="optional-details"><summary>Add technical context <span>optional</span></summary><div className="optional-fields"><div className="form-grid-2"><label>Current PMS / tools<input value={currentStack} onChange={e=>setCurrentStack(e.target.value)} placeholder="Cloudbeds, Opera, Booking.com..." className="setup-field"/></label><label>Past-guest database<input value={databaseSize} onChange={e=>setDatabaseSize(e.target.value)} placeholder="3,000 contacts / not sure" className="setup-field"/></label></div><label>Anything else we should know?<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} placeholder="Current bottleneck, desired outcome or timing." className="setup-field"/></label></div></details>
  <div className="setup-actions"><button type="submit" className="buy-button">Request setup review →</button><button type="button" onClick={copyRequest} className="buy-button secondary-button">{copied?"Request copied":"Copy request"}</button></div>
  <p className="form-note">We never ask for passwords, payment details or guest-level data at this stage. Your email app opens with the request prepared for hello@guestflowsystems.com.</p>
 </form>;
}